name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_run:
    workflows:
      - PR
    types:
      - completed
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install packages
        run: npm ci
      - name: Run lint
        run: npm run lint
